apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:mysql://mysql-db.c5ce6muoklt7.eu-west-3.rds.amazonaws.com:3306/restaurantdb
  foodcataloguedb_url: jdbc:mysql://mysql-db.c5ce6muoklt7.eu-west-3.rds.amazonaws.com:3306/fooddb
  userdb_url: jdbc:mysql://mysql-db.c5ce6muoklt7.eu-west-3.rds.amazonaws.com:3306/userdb
  orderdb_url: mongodb+srv://admin:Lavanya123@cluster0.hqxrg9j.mongodb.net/?retryWrites=true&w=majority
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka

  
  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
  